apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
  namespace: eduhelper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
        image: 397789365835.dkr.ecr.ap-southeast-1.amazonaws.com/esd-eduhelper-eks-ecr-production:notes
        imagePullPolicy: Always
        ports:
        - containerPort: 50052
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: DB_NAME
                name: eks-secrets
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                key: DB_HOST
                name: eks-secrets
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: DB_USERNAME
                name: eks-secrets
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
                name: eks-secrets
          - name: S3_BUCKET_NAME
            value: esd-eduhelper-notes-bucket
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50052"]
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50052"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
status: {}